#! /bin/sh
# Get last set pywal colors at start
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#
#FB=`xrdb -query | grep -E "^\*color7" | cut -d':' -f2 | sed -e 's/^[[:space:]]*//'`
#NB=`xrdb -query | grep -E "^\*color0" | cut -d':' -f2 | sed -e 's/^[[:space:]]*//'`

bspc config border_width         2
bspc config window_gap          12

#bspc config focused_border_color $FB
#bspc config normal_border_color $NB
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color7"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config presel_feedback_color $NB
bspc config presel_feedback_color "$color0"
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Steam desktop='^5'
bspc rule -a mpv state=floating
bspc rule -a feh state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# moved polybar startup to ../polybar/launch.sh
# as suggested in polybar wiki
# killall polybar && polybar main -q &
if ! pgrep -x "polybar" > /dev/null
then
    $HOME/.config/polybar/launch.sh
else
    killall polybar && $HOME/.config/polybar/launch.sh
fi

# adding sxhkd here so when I edit sxhkdrc I don't lose it
# if I close the terminal I ran it from.
if pgrep -x "sxhkd" > /dev/null
then
    killall sxhkd && sxhkd &
else
    sxhkd &
fi

# Dunst
if pgrep -x "dunst" > /dev/null
then
    killall dunst && dunst &
else
    dunst &
fi

#compton -b

